### ISSUE TITLE
Cannot locate the paired context files

### ISSUE THREAD

**Issue by brigmecham** [KihoPark/linear_rep_geometry#1]
How can I access the paired context files referenced in the measurement jupyter notebook?

Thanks!

**Comment by KihoPark** [comment]
Oh, sorry. Let me check if the context files are large to upload. If not, I can upload them!

**Comment by KihoPark** [comment]
I uploaded `paired_contexts` for the measurement experiment!

**Comment by brigmecham** [comment]
Thanks!
